/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * VsmfUpdateError.h
 *
 *
 */

#ifndef VsmfUpdateError_H_
#define VsmfUpdateError_H_

#include "NgApCause.h"
#include "ProblemDetails.h"
#include "RefToBinaryData.h"
#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace oai {
namespace smf_server {
namespace model {

/// <summary>
///
/// </summary>
class VsmfUpdateError {
 public:
  VsmfUpdateError();
  virtual ~VsmfUpdateError();

  void validate();

  /////////////////////////////////////////////
  /// VsmfUpdateError members

  /// <summary>
  ///
  /// </summary>
  oai::model::common::ProblemDetails getError() const;
  void setError(oai::model::common::ProblemDetails const& value);
  /// <summary>
  ///
  /// </summary>
  int32_t getPti() const;
  void setPti(int32_t const value);
  bool ptiIsSet() const;
  void unsetPti();
  /// <summary>
  ///
  /// </summary>
  std::string getN1smCause() const;
  void setN1smCause(std::string const& value);
  bool n1smCauseIsSet() const;
  void unsetN1smCause();
  /// <summary>
  ///
  /// </summary>
  oai::model::common::RefToBinaryData getN1SmInfoFromUe() const;
  void setN1SmInfoFromUe(oai::model::common::RefToBinaryData const& value);
  bool n1SmInfoFromUeIsSet() const;
  void unsetN1SmInfoFromUe();
  /// <summary>
  ///
  /// </summary>
  oai::model::common::RefToBinaryData getUnknownN1SmInfo() const;
  void setUnknownN1SmInfo(oai::model::common::RefToBinaryData const& value);
  bool unknownN1SmInfoIsSet() const;
  void unsetUnknownN1SmInfo();
  /// <summary>
  ///
  /// </summary>
  std::vector<int32_t>& getFailedToAssignEbiList();
  bool failedToAssignEbiListIsSet() const;
  void unsetFailedToAssignEbiList();
  /// <summary>
  ///
  /// </summary>
  oai::model::common::NgApCause getNgApCause() const;
  void setNgApCause(oai::model::common::NgApCause const& value);
  bool ngApCauseIsSet() const;
  void unsetNgApCause();
  /// <summary>
  ///
  /// </summary>
  int32_t get5gMmCauseValue() const;
  void set5gMmCauseValue(int32_t const value);
  bool _5gMmCauseValueIsSet() const;
  void unset_5gMmCauseValue();
  /// <summary>
  ///
  /// </summary>
  std::string getRecoveryTime() const;
  void setRecoveryTime(std::string const& value);
  bool recoveryTimeIsSet() const;
  void unsetRecoveryTime();

  friend void to_json(nlohmann::json& j, const VsmfUpdateError& o);
  friend void from_json(const nlohmann::json& j, VsmfUpdateError& o);

 protected:
  oai::model::common::ProblemDetails m_Error;

  int32_t m_Pti;
  bool m_PtiIsSet;
  std::string m_N1smCause;
  bool m_N1smCauseIsSet;
  oai::model::common::RefToBinaryData m_N1SmInfoFromUe;
  bool m_N1SmInfoFromUeIsSet;
  oai::model::common::RefToBinaryData m_UnknownN1SmInfo;
  bool m_UnknownN1SmInfoIsSet;
  std::vector<int32_t> m_FailedToAssignEbiList;
  bool m_FailedToAssignEbiListIsSet;
  oai::model::common::NgApCause m_NgApCause;
  bool m_NgApCauseIsSet;
  int32_t m__5gMmCauseValue;
  bool m__5gMmCauseValueIsSet;
  std::string m_RecoveryTime;
  bool m_RecoveryTimeIsSet;
};

}  // namespace model
}  // namespace smf_server
}  // namespace oai

#endif /* VsmfUpdateError_H_ */
