edge-scenario:
  routeToLocs:
  - dnai: access 
  - dnai: ulcl
  - dnai: aupf2
  - dnai: edge

internet-scenario:
  routeToLocs:
    - dnai: access
    - dnai: ulcl
    - dnai: aupf1
    - dnai: internet
