/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ComplexQuery.h
 *
 *
 */

#ifndef ComplexQuery_H_
#define ComplexQuery_H_

#include "CnfUnit.h"
#include "Dnf.h"
#include <vector>
#include "Cnf.h"
#include "DnfUnit.h"
#include <nlohmann/json.hpp>

namespace oai::model::common {

/// <summary>
///
/// </summary>
class ComplexQuery {
 public:
  ComplexQuery();
  virtual ~ComplexQuery() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const ComplexQuery& rhs) const;
  bool operator!=(const ComplexQuery& rhs) const;

  /////////////////////////////////////////////
  /// ComplexQuery members

  /// <summary>
  ///
  /// </summary>
  std::vector<oai::model::common::CnfUnit> getCnfUnits() const;
  void setCnfUnits(std::vector<oai::model::common::CnfUnit> const& value);
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::model::common::DnfUnit> getDnfUnits() const;
  void setDnfUnits(std::vector<oai::model::common::DnfUnit> const& value);

  friend void to_json(nlohmann::json& j, const ComplexQuery& o);
  friend void from_json(const nlohmann::json& j, ComplexQuery& o);

 protected:
  std::vector<oai::model::common::CnfUnit> m_CnfUnits;

  std::vector<oai::model::common::DnfUnit> m_DnfUnits;
};

}  // namespace oai::model::common

#endif /* ComplexQuery_H_ */
