/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "EcgiRm.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model::common {

EcgiRm::EcgiRm() {
  m_EutraCellId = "";
  m_Nid         = "";
  m_NidIsSet    = false;
}

void EcgiRm::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::model::common::helpers::ValidationException(msg.str());
  }
}

bool EcgiRm::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool EcgiRm::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success                  = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "EcgiRm" : pathPrefix;

  /* EutraCellId */ {
    const std::string& value           = m_EutraCellId;
    const std::string currentValuePath = _pathPrefix + ".eutraCellId";
  }

  if (nidIsSet()) {
    const std::string& value           = m_Nid;
    const std::string currentValuePath = _pathPrefix + ".nid";
  }

  return success;
}

bool EcgiRm::operator==(const EcgiRm& rhs) const {
  return

      (getPlmnId() == rhs.getPlmnId()) &&

      (getEutraCellId() == rhs.getEutraCellId()) &&

      ((!nidIsSet() && !rhs.nidIsSet()) ||
       (nidIsSet() && rhs.nidIsSet() && getNid() == rhs.getNid()))

          ;
}

bool EcgiRm::operator!=(const EcgiRm& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const EcgiRm& o) {
  j                = nlohmann::json();
  j["plmnId"]      = o.m_PlmnId;
  j["eutraCellId"] = o.m_EutraCellId;
  if (o.nidIsSet()) j["nid"] = o.m_Nid;
}

void from_json(const nlohmann::json& j, EcgiRm& o) {
  j.at("plmnId").get_to(o.m_PlmnId);
  j.at("eutraCellId").get_to(o.m_EutraCellId);
  if (j.find("nid") != j.end()) {
    j.at("nid").get_to(o.m_Nid);
    o.m_NidIsSet = true;
  }
}

oai::model::common::PlmnId EcgiRm::getPlmnId() const {
  return m_PlmnId;
}
void EcgiRm::setPlmnId(oai::model::common::PlmnId const& value) {
  m_PlmnId = value;
}
std::string EcgiRm::getEutraCellId() const {
  return m_EutraCellId;
}
void EcgiRm::setEutraCellId(std::string const& value) {
  m_EutraCellId = value;
}
std::string EcgiRm::getNid() const {
  return m_Nid;
}
void EcgiRm::setNid(std::string const& value) {
  m_Nid      = value;
  m_NidIsSet = true;
}
bool EcgiRm::nidIsSet() const {
  return m_NidIsSet;
}
void EcgiRm::unsetNid() {
  m_NidIsSet = false;
}

}  // namespace oai::model::common
