/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * BackupAmfInfo.h
 *
 *
 */

#ifndef BackupAmfInfo_H_
#define BackupAmfInfo_H_

#include <string>
#include <vector>
#include "Guami.h"
#include <nlohmann/json.hpp>

namespace oai::model::common {

/// <summary>
///
/// </summary>
class BackupAmfInfo {
 public:
  BackupAmfInfo();
  virtual ~BackupAmfInfo() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const BackupAmfInfo& rhs) const;
  bool operator!=(const BackupAmfInfo& rhs) const;

  /////////////////////////////////////////////
  /// BackupAmfInfo members

  /// <summary>
  ///
  /// </summary>
  std::string getBackupAmf() const;
  void setBackupAmf(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::model::common::Guami> getGuamiList() const;
  void setGuamiList(std::vector<oai::model::common::Guami> const& value);
  bool guamiListIsSet() const;
  void unsetGuamiList();

  friend void to_json(nlohmann::json& j, const BackupAmfInfo& o);
  friend void from_json(const nlohmann::json& j, BackupAmfInfo& o);

 protected:
  std::string m_BackupAmf;

  std::vector<oai::model::common::Guami> m_GuamiList;
  bool m_GuamiListIsSet;
};

}  // namespace oai::model::common

#endif /* BackupAmfInfo_H_ */
