/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * LineTypeRm.h
 *
 *
 */

#ifndef LineTypeRm_H_
#define LineTypeRm_H_

#include "LineType.h"
#include "NullValue.h"
#include <nlohmann/json.hpp>

namespace oai::model::common {

/// <summary>
///
/// </summary>
class LineTypeRm : public LineType {
 public:
  LineTypeRm();
  virtual ~LineTypeRm() = default;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(
      std::stringstream& msg, const std::string& pathPrefix) const override;
  /////////////////////////////////////////////
  /// LineTypeRm members

  friend void to_json(nlohmann::json& j, const LineTypeRm& o);
  friend void from_json(const nlohmann::json& j, LineTypeRm& o);

 protected:
};

}  // namespace oai::model::common

#endif /* LineTypeRm_H_ */
