/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NotificationControlRm.h
 *
 *
 */

#ifndef NotificationControlRm_H_
#define NotificationControlRm_H_

#include "NotificationControl.h"
#include "NullValue.h"
#include <nlohmann/json.hpp>

namespace oai::model::common {

/// <summary>
///
/// </summary>
class NotificationControlRm : public NotificationControl {
 public:
  NotificationControlRm();
  virtual ~NotificationControlRm() = default;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(
      std::stringstream& msg, const std::string& pathPrefix) const override;

  /////////////////////////////////////////////
  /// NotificationControlRm members

  friend void to_json(nlohmann::json& j, const NotificationControlRm& o);
  friend void from_json(const nlohmann::json& j, NotificationControlRm& o);

 protected:
};

}  // namespace oai::model::common

#endif /* NotificationControlRm_H_ */
