/**
 * Nudsf_DataRepository
 * Nudsf Data Repository Service.   © 2022, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * RecordOperation.h
 *
 * Indicate operation made on a record
 */

#ifndef RecordOperation_H_
#define RecordOperation_H_

#include <nlohmann/json.hpp>

namespace oai::model::udsf {

/// <summary>
/// Indicate operation made on a record
/// </summary>
class RecordOperation {
 public:
  RecordOperation();
  virtual ~RecordOperation() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const RecordOperation& rhs) const;
  bool operator!=(const RecordOperation& rhs) const;

  /////////////////////////////////////////////
  /// RecordOperation members

  friend void to_json(nlohmann::json& j, const RecordOperation& o);
  friend void from_json(const nlohmann::json& j, RecordOperation& o);

 protected:
};

}  // namespace oai::model::udsf

#endif /* RecordOperation_H_ */
