apiVersion: v1
kind: ServiceAccount
metadata:
  name: ims-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ims-privileged-role
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ims-privileged-binding
subjects:
- kind: ServiceAccount
  name: ims-sa
  namespace: oaicicd-core
roleRef:
  kind: Role
  name: ims-privileged-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ims-net1
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "bond0",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "172.21.6.202/22"

                }
        ]
      }
    }'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ims-cm
data:
   script.sh: |
     #!/bin/sh
     apk add --update --quiet asterisk
     asterisk -fp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ims-sip
data:
   sip.conf: |
      [general]
      language=fr
      tcpenable=yes
      tcpbindaddr=0.0.0.0
      tcpbindport=5060
      srvlookup=yes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ims-users
data:
   users.conf: |
      [001010000000100]
      fullname = tom
      hassip = yes
      context = users
      host = dynamic
      transport=tcp
      [001010000000101]
      fullname = harry
      hassip = yes
      context = users
      host = dynamic
      transport=tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims
spec:
  selector:
    matchLabels:
      app: ims
  template:
    metadata:
      labels:
        app: ims
      annotations:
        k8s.v1.cni.cncf.io/networks: >-
            [{
                "name": "ims-net1",
                "default-route": ["172.21.7.254"]
            }]
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      serviceAccountName: ims-sa 
      containers:
      - name: ims
        image: quay.io/quay/ubuntu:latest
        securityContext:
          privileged: false
        #command: ["./tmp/script.sh"]
        command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
        volumeMounts:
        - mountPath: /etc/asterisk/sip.conf
          name: sip
          subPath: sip.conf
        - mountPath: /etc/asterisk/users.conf
          name: users
          subPath: users.conf
        - mountPath: /tmp/script.sh
          name: startup
          subPath: script.sh
      volumes:
        - name: sip
          configMap:
            name: ims-sip
        - name: users
          configMap:
            name: ims-users
        - name: startup
          configMap:
            name: ims-cm
            defaultMode: 0777
