# In this docker-compose upf is not privileged access, it is good example for security purpose
version: '3.8'
services:
    mysql:
        container_name: "mysql"
        image: mysql:8.0
        volumes:
            - ./database/oai_db1.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ./healthscripts/mysql-healthcheck1.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 30
        networks:
            public_net:
                ipv4_address: 192.168.70.131
    oai-amf:
        container_name: "oai-amf"
        image: oaisoftwarealliance/oai-amf:v2.0.0
        volumes:
            - ./conf/mini_nonrf_config.yaml:/openair-amf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - mysql
        networks:
            public_net:
                ipv4_address: 192.168.70.132
    oai-smf:
        container_name: "oai-smf"
        image: oaisoftwarealliance/oai-smf:v2.0.0
        volumes:
            - ./conf/mini_nonrf_config.yaml:/openair-smf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-amf
        networks:
            public_net:
                ipv4_address: 192.168.70.133
        # TODO we need this for now until SMF does not resolve UPF upon start anymore
        extra_hosts:
            - "oai-upf:192.168.70.134"
    oai-upf:
        container_name: "oai-upf"
        image: oaisoftwarealliance/oai-upf:v2.0.0
        volumes:
            - ./conf/mini_nonrf_config.yaml:/openair-upf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-smf
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
            - NET_RAW
        cap_drop:
            - ALL
        devices:
            - /dev/net/tun:/dev/net/tun
        sysctls:
            - net.ipv4.conf.eth0.rp_filter=0
            - net.ipv4.conf.all.forwarding=1
            - net.ipv4.conf.all.send_redirects=0
            - net.ipv4.conf.default.send_redirects=0
            - net.ipv4.conf.all.accept_redirects=0
            - net.ipv4.conf.default.accept_redirects=0
        networks:
            public_net:
                ipv4_address: 192.168.70.134
networks:
    # public_net:
    #     external:
    #         name: demo-oai-public-net
    public_net:
        driver: bridge
        name: demo-oai-public-net
        ipam:
            config:
                - subnet: 192.168.70.128/26
        driver_opts:
            com.docker.network.bridge.name: "demo-oai"
