/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Ipv6PrefixRm.h
 *
 *
 */

#ifndef Ipv6PrefixRm_H_
#define Ipv6PrefixRm_H_

#include <nlohmann/json.hpp>
#include "Ipv6Prefix.h"

namespace oai::model::common {

/// <summary>
///
/// </summary>
class Ipv6PrefixRm : public Ipv6Prefix {
 public:
  Ipv6PrefixRm();
  virtual ~Ipv6PrefixRm() = default;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(
      std::stringstream& msg, const std::string& pathPrefix) const override;
  /////////////////////////////////////////////
  /// Ipv6PrefixRm members

  friend void to_json(nlohmann::json& j, const Ipv6PrefixRm& o);
  friend void from_json(const nlohmann::json& j, Ipv6PrefixRm& o);

 protected:
};

}  // namespace oai::model::common

#endif /* Ipv6PrefixRm_H_ */
