apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-cu.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: n2
      port: 36412
      targetPort: 36412
      protocol: SCTP
    - name: n3
      port: 2152
      targetPort: 2152
      protocol: UDP
    - name: f1
      port: 2153
      targetPort: 2153
      protocol: UDP
  selector:
    {{- include "oai-cu.selectorLabels" . | nindent 4 }}
