/**
 * Namf_Communication
 * AMF Communication Service © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ConfiguredSnssai.h
 *
 *
 */

#ifndef ConfiguredSnssai_H_
#define ConfiguredSnssai_H_

#include "Snssai.h"
#include <nlohmann/json.hpp>

namespace oai {
namespace amf {
namespace model {

/// <summary>
///
/// </summary>
class ConfiguredSnssai {
 public:
  ConfiguredSnssai();
  virtual ~ConfiguredSnssai() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const ConfiguredSnssai& rhs) const;
  bool operator!=(const ConfiguredSnssai& rhs) const;

  /////////////////////////////////////////////
  /// ConfiguredSnssai members

  /// <summary>
  ///
  /// </summary>
  oai::model::common::Snssai getConfiguredSnssai() const;
  void setConfiguredSnssai(oai::model::common::Snssai const& value);
  /// <summary>
  ///
  /// </summary>
  oai::model::common::Snssai getMappedHomeSnssai() const;
  void setMappedHomeSnssai(oai::model::common::Snssai const& value);
  bool mappedHomeSnssaiIsSet() const;
  void unsetMappedHomeSnssai();

  friend void to_json(nlohmann::json& j, const ConfiguredSnssai& o);
  friend void from_json(const nlohmann::json& j, ConfiguredSnssai& o);

 protected:
  oai::model::common::Snssai m_ConfiguredSnssai;

  oai::model::common::Snssai m_MappedHomeSnssai;
  bool m_MappedHomeSnssaiIsSet;
};

}  // namespace model
}  // namespace amf
}  // namespace oai

#endif /* ConfiguredSnssai_H_ */
