/**
 * Namf_Communication
 * AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.8
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * N2RanInformation.h
 *
 *
 */

#ifndef N2RanInformation_H_
#define N2RanInformation_H_

#include "N2InfoContent.h"
#include <nlohmann/json.hpp>

namespace oai::amf::model {

/// <summary>
///
/// </summary>
class N2RanInformation {
 public:
  N2RanInformation();
  virtual ~N2RanInformation() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const N2RanInformation& rhs) const;
  bool operator!=(const N2RanInformation& rhs) const;

  /////////////////////////////////////////////
  /// N2RanInformation members

  /// <summary>
  ///
  /// </summary>
  oai::amf::model::N2InfoContent getN2InfoContent() const;
  void setN2InfoContent(oai::amf::model::N2InfoContent const& value);

  friend void to_json(nlohmann::json& j, const N2RanInformation& o);
  friend void from_json(const nlohmann::json& j, N2RanInformation& o);

 protected:
  oai::amf::model::N2InfoContent m_N2InfoContent;
};

}  // namespace oai::amf::model

#endif /* N2RanInformation_H_ */
