/**
 * Namf_Communication
 * AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.8
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * N2SmInformation.h
 *
 *
 */

#ifndef N2SmInformation_H_
#define N2SmInformation_H_

#include "N2InfoContent.h"
#include "Snssai.h"
#include <nlohmann/json.hpp>

namespace oai::amf::model {

/// <summary>
///
/// </summary>
class N2SmInformation {
 public:
  N2SmInformation();
  virtual ~N2SmInformation() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const N2SmInformation& rhs) const;
  bool operator!=(const N2SmInformation& rhs) const;

  /////////////////////////////////////////////
  /// N2SmInformation members

  /// <summary>
  ///
  /// </summary>
  int32_t getPduSessionId() const;
  void setPduSessionId(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  oai::amf::model::N2InfoContent getN2InfoContent() const;
  void setN2InfoContent(oai::amf::model::N2InfoContent const& value);
  bool n2InfoContentIsSet() const;
  void unsetN2InfoContent();
  /// <summary>
  ///
  /// </summary>
  oai::model::common::Snssai getSNssai() const;
  void setSNssai(oai::model::common::Snssai const& value);
  bool sNssaiIsSet() const;
  void unsetSNssai();
  /// <summary>
  ///
  /// </summary>
  oai::model::common::Snssai getHomePlmnSnssai() const;
  void setHomePlmnSnssai(oai::model::common::Snssai const& value);
  bool homePlmnSnssaiIsSet() const;
  void unsetHomePlmnSnssai();
  /// <summary>
  ///
  /// </summary>
  oai::model::common::Snssai getIwkSnssai() const;
  void setIwkSnssai(oai::model::common::Snssai const& value);
  bool iwkSnssaiIsSet() const;
  void unsetIwkSnssai();
  /// <summary>
  ///
  /// </summary>
  bool isSubjectToHo() const;
  void setSubjectToHo(bool const value);
  bool subjectToHoIsSet() const;
  void unsetSubjectToHo();

  friend void to_json(nlohmann::json& j, const N2SmInformation& o);
  friend void from_json(const nlohmann::json& j, N2SmInformation& o);

 protected:
  int32_t m_PduSessionId;

  oai::amf::model::N2InfoContent m_N2InfoContent;
  bool m_N2InfoContentIsSet;
  oai::model::common::Snssai m_SNssai;
  bool m_SNssaiIsSet;
  oai::model::common::Snssai m_HomePlmnSnssai;
  bool m_HomePlmnSnssaiIsSet;
  oai::model::common::Snssai m_IwkSnssai;
  bool m_IwkSnssaiIsSet;
  bool m_SubjectToHo;
  bool m_SubjectToHoIsSet;
};

}  // namespace oai::amf::model

#endif /* N2SmInformation_H_ */
