/**
 * Namf_Communication
 * AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.8
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "NgapIeType.h"
#include "Helpers.h"

#include <sstream>

namespace oai::amf::model {

NgapIeType::NgapIeType() {}

void NgapIeType::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::model::common::helpers::ValidationException(msg.str());
  }
}

bool NgapIeType::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool NgapIeType::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "NgapIeType" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool NgapIeType::operator==(const NgapIeType& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool NgapIeType::operator!=(const NgapIeType& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const NgapIeType& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, NgapIeType& o) {
  from_json(j, o.m_value);
}

NgapIeType_anyOf NgapIeType::getValue() const {
  return m_value;
}

void NgapIeType::setValue(NgapIeType_anyOf value) {
  m_value = value;
}

NgapIeType_anyOf::eNgapIeType_anyOf NgapIeType::getEnumValue() const {
  return m_value.getValue();
}

void NgapIeType::setEnumValue(NgapIeType_anyOf::eNgapIeType_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::amf::model
