/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2023, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "FlowDirection_anyOf.h"
#include "Helpers.h"
#include <stdexcept>
#include <sstream>

namespace oai::model::pcf {

FlowDirection_anyOf::FlowDirection_anyOf() {}

void FlowDirection_anyOf::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::model::common::helpers::ValidationException(msg.str());
  }
}

bool FlowDirection_anyOf::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool FlowDirection_anyOf::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "FlowDirection_anyOf" : pathPrefix;

  if (m_value == FlowDirection_anyOf::eFlowDirection_anyOf::
                     INVALID_VALUE_OPENAPI_GENERATED) {
    success = false;
    msg << _pathPrefix << ": has no value;";
  }

  return success;
}

bool FlowDirection_anyOf::operator==(const FlowDirection_anyOf& rhs) const {
  return getValue() == rhs.getValue()

      ;
}

bool FlowDirection_anyOf::operator!=(const FlowDirection_anyOf& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const FlowDirection_anyOf& o) {
  j = nlohmann::json();

  switch (o.getValue()) {
    case FlowDirection_anyOf::eFlowDirection_anyOf::
        INVALID_VALUE_OPENAPI_GENERATED:
      j = "INVALID_VALUE_OPENAPI_GENERATED";
      break;
    case FlowDirection_anyOf::eFlowDirection_anyOf::DOWNLINK:
      j = "DOWNLINK";
      break;
    case FlowDirection_anyOf::eFlowDirection_anyOf::UPLINK:
      j = "UPLINK";
      break;
    case FlowDirection_anyOf::eFlowDirection_anyOf::BIDIRECTIONAL:
      j = "BIDIRECTIONAL";
      break;
    case FlowDirection_anyOf::eFlowDirection_anyOf::UNSPECIFIED:
      j = "UNSPECIFIED";
      break;
    case FlowDirection_anyOf::eFlowDirection_anyOf::NULL_VALUE:
      j = nullptr;
      break;
  }
}

void from_json(const nlohmann::json& j, FlowDirection_anyOf& o) {
  if (j.is_null()) {
    o.setValue(FlowDirection_anyOf::eFlowDirection_anyOf::NULL_VALUE);
    return;
  }

  auto s = j.get<std::string>();
  if (s == "DOWNLINK") {
    o.setValue(FlowDirection_anyOf::eFlowDirection_anyOf::DOWNLINK);
  } else if (s == "UPLINK") {
    o.setValue(FlowDirection_anyOf::eFlowDirection_anyOf::UPLINK);
  } else if (s == "BIDIRECTIONAL") {
    o.setValue(FlowDirection_anyOf::eFlowDirection_anyOf::BIDIRECTIONAL);
  } else if (s == "UNSPECIFIED") {
    o.setValue(FlowDirection_anyOf::eFlowDirection_anyOf::UNSPECIFIED);
  } else if (s == "null") {
    o.setValue(FlowDirection_anyOf::eFlowDirection_anyOf::NULL_VALUE);
  } else {
    std::stringstream ss;
    ss << "Unexpected value " << s << " in json"
       << " cannot be converted to enum of type"
       << " FlowDirection_anyOf::eFlowDirection_anyOf";
    throw std::invalid_argument(ss.str());
  }
}

FlowDirection_anyOf::eFlowDirection_anyOf FlowDirection_anyOf::getValue()
    const {
  return m_value;
}
void FlowDirection_anyOf::setValue(
    FlowDirection_anyOf::eFlowDirection_anyOf value) {
  m_value = value;
}

}  // namespace oai::model::pcf
