/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2023, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "NotificationControlIndication.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model::pcf {

NotificationControlIndication::NotificationControlIndication() {}

void NotificationControlIndication::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::model::common::helpers::ValidationException(msg.str());
  }
}

bool NotificationControlIndication::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool NotificationControlIndication::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "NotificationControlIndication" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool NotificationControlIndication::operator==(
    const NotificationControlIndication& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool NotificationControlIndication::operator!=(
    const NotificationControlIndication& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const NotificationControlIndication& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, NotificationControlIndication& o) {
  from_json(j, o.m_value);
}

NotificationControlIndication_anyOf NotificationControlIndication::getValue()
    const {
  return m_value;
}

void NotificationControlIndication::setValue(
    NotificationControlIndication_anyOf value) {
  m_value = value;
}

NotificationControlIndication_anyOf::eNotificationControlIndication_anyOf
NotificationControlIndication::getEnumValue() const {
  return m_value.getValue();
}

void NotificationControlIndication::setEnumValue(
    NotificationControlIndication_anyOf::eNotificationControlIndication_anyOf
        value) {
  m_value.setValue(value);
}

}  // namespace oai::model::pcf
