/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2023, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * RequestedRuleDataType_anyOf.h
 *
 *
 */

#ifndef RequestedRuleDataType_anyOf_H_
#define RequestedRuleDataType_anyOf_H_

#include <nlohmann/json.hpp>

namespace oai::model::pcf {

/// <summary>
///
/// </summary>
class RequestedRuleDataType_anyOf {
 public:
  RequestedRuleDataType_anyOf();
  virtual ~RequestedRuleDataType_anyOf() = default;

  enum class eRequestedRuleDataType_anyOf {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    CH_ID,
    MS_TIME_ZONE,
    USER_LOC_INFO,
    RES_RELEASE,
    SUCC_RES_ALLO,
    EPS_FALLBACK
  };

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const RequestedRuleDataType_anyOf& rhs) const;
  bool operator!=(const RequestedRuleDataType_anyOf& rhs) const;

  /////////////////////////////////////////////
  /// RequestedRuleDataType_anyOf members

  RequestedRuleDataType_anyOf::eRequestedRuleDataType_anyOf getValue() const;
  void setValue(
      RequestedRuleDataType_anyOf::eRequestedRuleDataType_anyOf value);

  friend void to_json(nlohmann::json& j, const RequestedRuleDataType_anyOf& o);
  friend void from_json(
      const nlohmann::json& j, RequestedRuleDataType_anyOf& o);

 protected:
  RequestedRuleDataType_anyOf::eRequestedRuleDataType_anyOf m_value =
      RequestedRuleDataType_anyOf::eRequestedRuleDataType_anyOf::
          INVALID_VALUE_OPENAPI_GENERATED;
};

}  // namespace oai::model::pcf

#endif /* RequestedRuleDataType_anyOf_H_ */
