/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2023, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "FlowStatus.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model::pcf {

FlowStatus::FlowStatus() {}

void FlowStatus::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::model::common::helpers::ValidationException(msg.str());
  }
}

bool FlowStatus::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool FlowStatus::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "FlowStatus" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool FlowStatus::operator==(const FlowStatus& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool FlowStatus::operator!=(const FlowStatus& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const FlowStatus& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, FlowStatus& o) {
  from_json(j, o.m_value);
}

FlowStatus_anyOf FlowStatus::getValue() const {
  return m_value;
}

void FlowStatus::setValue(FlowStatus_anyOf value) {
  m_value = value;
}

FlowStatus_anyOf::eFlowStatus_anyOf FlowStatus::getEnumValue() const {
  return m_value.getValue();
}

void FlowStatus::setEnumValue(FlowStatus_anyOf::eFlowStatus_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::model::pcf
