apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  {{ (.Files.Glob "config.yaml").AsConfig | indent 2 | trim }}
  {{ (.Files.Glob "nssf_slice_config.yaml").AsConfig | indent 2 | trim }}