/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NotificationControl.h
 *
 *
 */

#ifndef NotificationControl_H_
#define NotificationControl_H_

#include "NotificationControl_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::model::common {

/// <summary>
///
/// </summary>
class NotificationControl {
 public:
  NotificationControl();
  virtual ~NotificationControl() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  virtual bool validate(
      std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const NotificationControl& rhs) const;
  bool operator!=(const NotificationControl& rhs) const;

  /////////////////////////////////////////////
  /// NotificationControl members

  NotificationControl_anyOf getValue() const;
  void setValue(NotificationControl_anyOf value);
  NotificationControl_anyOf::eNotificationControl_anyOf getEnumValue() const;
  void setEnumValue(
      NotificationControl_anyOf::eNotificationControl_anyOf value);
  friend void to_json(nlohmann::json& j, const NotificationControl& o);
  friend void from_json(const nlohmann::json& j, NotificationControl& o);
  friend void to_json(nlohmann::json& j, const NotificationControl_anyOf& o);
  friend void from_json(const nlohmann::json& j, NotificationControl_anyOf& o);

 protected:
  NotificationControl_anyOf m_value;
};

}  // namespace oai::model::common

#endif /* NotificationControl_H_ */
