apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  cuup.conf: |
      Active_gNBs = ( "{{ .Values.config.cuupName}}");
      # Asn1_verbosity, choice in: none, info, annoying
      Asn1_verbosity = "none";
      sa = 1;

      gNBs =
      (
       {
          ////////// Identification parameters:
          gNB_ID = 0xe00;
          gNB_CU_UP_ID = 0xe00;

      #     cell_type =  "CELL_MACRO_GNB";

          gNB_name  =  "{{ .Values.config.cuupName}}";

          // Tracking area code, 0x0000 and 0xfffe are reserved values
          tracking_area_code  = {{ .Values.config.tac}};
          plmn_list = ({ mcc = {{ .Values.config.mcc}}; mnc = {{ .Values.config.mnc}}; mnc_length = 2; snssaiList = ({ sst = {{ .Values.config.sst}} }) });


          tr_s_preference = "f1";

          local_s_if_name = "{{ .Values.config.f1IfName}}";
          local_s_address = "@F1_IP_ADDRESS@";
          remote_s_address = "127.0.0.1";
          local_s_portc   = 501;
          local_s_portd   = {{ .Values.config.f1cuPort}};
          remote_s_portc  = 500;
          remote_s_portd  = {{ .Values.config.f1duPort}};

          # ------- SCTP definitions
          SCTP :
          {
              # Number of streams to use in input/output
              SCTP_INSTREAMS  = 2;
              SCTP_OUTSTREAMS = 2;
          };

          E1_INTERFACE =
          (
            {
              type = "up";
              ipv4_cucp = "@CU_CP_IP_ADDRESS@";
              ipv4_cuup = "@CU_UP_IP_ADDRESS@";
            }
          )

          NETWORK_INTERFACES :
          {
            GNB_INTERFACE_NAME_FOR_NG_AMF            = "{{ .Values.config.n2IfName}}";
            GNB_IPV4_ADDRESS_FOR_NG_AMF              = "@N2_IP_ADDRESS@";
            GNB_INTERFACE_NAME_FOR_NGU               = "{{ .Values.config.n3IfName}}";
            GNB_IPV4_ADDRESS_FOR_NGU                 = "@N3_IP_ADDRESS@";
            GNB_PORT_FOR_S1U                         = 2152; # Spec 2152
          };
        }
      );

      log_config : {
        global_log_level = "info";
        pdcp_log_level   = "info";
        f1ap_log_level   = "info";
        ngap_log_level   = "info";
      };
