/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2023, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ReportingFrequency_anyOf.h
 *
 *
 */

#ifndef ReportingFrequency_anyOf_H_
#define ReportingFrequency_anyOf_H_

#include <nlohmann/json.hpp>

namespace oai::model::pcf {

/// <summary>
///
/// </summary>
class ReportingFrequency_anyOf {
 public:
  ReportingFrequency_anyOf();
  virtual ~ReportingFrequency_anyOf() = default;

  enum class eReportingFrequency_anyOf {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    EVENT_TRIGGERED,
    PERIODIC
  };

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const ReportingFrequency_anyOf& rhs) const;
  bool operator!=(const ReportingFrequency_anyOf& rhs) const;

  /////////////////////////////////////////////
  /// ReportingFrequency_anyOf members

  ReportingFrequency_anyOf::eReportingFrequency_anyOf getValue() const;
  void setValue(ReportingFrequency_anyOf::eReportingFrequency_anyOf value);

  friend void to_json(nlohmann::json& j, const ReportingFrequency_anyOf& o);
  friend void from_json(const nlohmann::json& j, ReportingFrequency_anyOf& o);

 protected:
  ReportingFrequency_anyOf::eReportingFrequency_anyOf m_value =
      ReportingFrequency_anyOf::eReportingFrequency_anyOf::
          INVALID_VALUE_OPENAPI_GENERATED;
};

}  // namespace oai::model::pcf

#endif /* ReportingFrequency_anyOf_H_ */
