/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2023, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SmPolicyAssociationReleaseCause.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model::pcf {

SmPolicyAssociationReleaseCause::SmPolicyAssociationReleaseCause() {}

void SmPolicyAssociationReleaseCause::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::model::common::helpers::ValidationException(msg.str());
  }
}

bool SmPolicyAssociationReleaseCause::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool SmPolicyAssociationReleaseCause::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "SmPolicyAssociationReleaseCause" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool SmPolicyAssociationReleaseCause::operator==(
    const SmPolicyAssociationReleaseCause& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool SmPolicyAssociationReleaseCause::operator!=(
    const SmPolicyAssociationReleaseCause& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SmPolicyAssociationReleaseCause& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, SmPolicyAssociationReleaseCause& o) {
  from_json(j, o.m_value);
}

SmPolicyAssociationReleaseCause_anyOf
SmPolicyAssociationReleaseCause::getValue() const {
  return m_value;
}

void SmPolicyAssociationReleaseCause::setValue(
    SmPolicyAssociationReleaseCause_anyOf value) {
  m_value = value;
}

SmPolicyAssociationReleaseCause_anyOf::eSmPolicyAssociationReleaseCause_anyOf
SmPolicyAssociationReleaseCause::getEnumValue() const {
  return m_value.getValue();
}

void SmPolicyAssociationReleaseCause::setEnumValue(
    SmPolicyAssociationReleaseCause_anyOf::
        eSmPolicyAssociationReleaseCause_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::model::pcf
