/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2023, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SessionRuleFailureCode.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model::pcf {

SessionRuleFailureCode::SessionRuleFailureCode() {}

void SessionRuleFailureCode::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::model::common::helpers::ValidationException(msg.str());
  }
}

bool SessionRuleFailureCode::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool SessionRuleFailureCode::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "SessionRuleFailureCode" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool SessionRuleFailureCode::operator==(
    const SessionRuleFailureCode& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool SessionRuleFailureCode::operator!=(
    const SessionRuleFailureCode& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SessionRuleFailureCode& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, SessionRuleFailureCode& o) {
  from_json(j, o.m_value);
}

SessionRuleFailureCode_anyOf SessionRuleFailureCode::getValue() const {
  return m_value;
}

void SessionRuleFailureCode::setValue(SessionRuleFailureCode_anyOf value) {
  m_value = value;
}

SessionRuleFailureCode_anyOf::eSessionRuleFailureCode_anyOf
SessionRuleFailureCode::getEnumValue() const {
  return m_value.getValue();
}

void SessionRuleFailureCode::setEnumValue(
    SessionRuleFailureCode_anyOf::eSessionRuleFailureCode_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::model::pcf
