/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2023, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "DnnSelectionMode_anyOf.h"
#include "Helpers.h"
#include <stdexcept>
#include <sstream>

namespace oai::model::smf {

DnnSelectionMode_anyOf::DnnSelectionMode_anyOf() {}

void DnnSelectionMode_anyOf::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::model::common::helpers::ValidationException(msg.str());
  }
}

bool DnnSelectionMode_anyOf::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool DnnSelectionMode_anyOf::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "DnnSelectionMode_anyOf" : pathPrefix;

  if (m_value == DnnSelectionMode_anyOf::eDnnSelectionMode_anyOf::
                     INVALID_VALUE_OPENAPI_GENERATED) {
    success = false;
    msg << _pathPrefix << ": has no value;";
  }

  return success;
}

bool DnnSelectionMode_anyOf::operator==(
    const DnnSelectionMode_anyOf& rhs) const {
  return getValue() == rhs.getValue()

      ;
}

bool DnnSelectionMode_anyOf::operator!=(
    const DnnSelectionMode_anyOf& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const DnnSelectionMode_anyOf& o) {
  j = nlohmann::json();

  switch (o.getValue()) {
    case DnnSelectionMode_anyOf::eDnnSelectionMode_anyOf::
        INVALID_VALUE_OPENAPI_GENERATED:
      j = "INVALID_VALUE_OPENAPI_GENERATED";
      break;
    case DnnSelectionMode_anyOf::eDnnSelectionMode_anyOf::VERIFIED:
      j = "VERIFIED";
      break;
    case DnnSelectionMode_anyOf::eDnnSelectionMode_anyOf::UE_DNN_NOT_VERIFIED:
      j = "UE_DNN_NOT_VERIFIED";
      break;
    case DnnSelectionMode_anyOf::eDnnSelectionMode_anyOf::NW_DNN_NOT_VERIFIED:
      j = "NW_DNN_NOT_VERIFIED";
      break;
  }
}

void from_json(const nlohmann::json& j, DnnSelectionMode_anyOf& o) {
  auto s = j.get<std::string>();
  if (s == "VERIFIED") {
    o.setValue(DnnSelectionMode_anyOf::eDnnSelectionMode_anyOf::VERIFIED);
  } else if (s == "UE_DNN_NOT_VERIFIED") {
    o.setValue(
        DnnSelectionMode_anyOf::eDnnSelectionMode_anyOf::UE_DNN_NOT_VERIFIED);
  } else if (s == "NW_DNN_NOT_VERIFIED") {
    o.setValue(
        DnnSelectionMode_anyOf::eDnnSelectionMode_anyOf::NW_DNN_NOT_VERIFIED);
  } else {
    std::stringstream ss;
    ss << "Unexpected value " << s << " in json"
       << " cannot be converted to enum of type"
       << " DnnSelectionMode_anyOf::eDnnSelectionMode_anyOf";
    throw std::invalid_argument(ss.str());
  }
}

DnnSelectionMode_anyOf::eDnnSelectionMode_anyOf
DnnSelectionMode_anyOf::getValue() const {
  return m_value;
}
void DnnSelectionMode_anyOf::setValue(
    DnnSelectionMode_anyOf::eDnnSelectionMode_anyOf value) {
  m_value = value;
}

}  // namespace oai::model::smf
