/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * GuamiRm.h
 *
 *
 */

#ifndef GuamiRm_H_
#define GuamiRm_H_

#include "PlmnIdNid.h"
#include <string>
#include "NullValue.h"
#include "Guami.h"
#include <nlohmann/json.hpp>

namespace oai::model::common {

/// <summary>
///
/// </summary>
class GuamiRm {
 public:
  GuamiRm();
  virtual ~GuamiRm() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const GuamiRm& rhs) const;
  bool operator!=(const GuamiRm& rhs) const;

  /////////////////////////////////////////////
  /// GuamiRm members

  /// <summary>
  ///
  /// </summary>
  oai::model::common::PlmnIdNid getPlmnId() const;
  void setPlmnId(oai::model::common::PlmnIdNid const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getAmfId() const;
  void setAmfId(std::string const& value);

  friend void to_json(nlohmann::json& j, const GuamiRm& o);
  friend void from_json(const nlohmann::json& j, GuamiRm& o);

 protected:
  oai::model::common::PlmnIdNid m_PlmnId;

  std::string m_AmfId;
};

}  // namespace oai::model::common

#endif /* GuamiRm_H_ */
