/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "GuamiRm.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model::common {

GuamiRm::GuamiRm() {
  m_AmfId = "";
}

void GuamiRm::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::model::common::helpers::ValidationException(msg.str());
  }
}

bool GuamiRm::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool GuamiRm::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success                  = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "GuamiRm" : pathPrefix;

  /* AmfId */ {
    const std::string& value           = m_AmfId;
    const std::string currentValuePath = _pathPrefix + ".amfId";
  }

  return success;
}

bool GuamiRm::operator==(const GuamiRm& rhs) const {
  return

      (getPlmnId() == rhs.getPlmnId()) &&

      (getAmfId() == rhs.getAmfId())

          ;
}

bool GuamiRm::operator!=(const GuamiRm& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const GuamiRm& o) {
  j           = nlohmann::json();
  j["plmnId"] = o.m_PlmnId;
  j["amfId"]  = o.m_AmfId;
}

void from_json(const nlohmann::json& j, GuamiRm& o) {
  j.at("plmnId").get_to(o.m_PlmnId);
  j.at("amfId").get_to(o.m_AmfId);
}

oai::model::common::PlmnIdNid GuamiRm::getPlmnId() const {
  return m_PlmnId;
}
void GuamiRm::setPlmnId(oai::model::common::PlmnIdNid const& value) {
  m_PlmnId = value;
}
std::string GuamiRm::getAmfId() const {
  return m_AmfId;
}
void GuamiRm::setAmfId(std::string const& value) {
  m_AmfId = value;
}

}  // namespace oai::model::common
