/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "NssaaStatusRm.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model::common {

NssaaStatusRm::NssaaStatusRm() {}

void NssaaStatusRm::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::model::common::helpers::ValidationException(msg.str());
  }
}

bool NssaaStatusRm::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool NssaaStatusRm::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "NssaaStatusRm" : pathPrefix;

  return success;
}

bool NssaaStatusRm::operator==(const NssaaStatusRm& rhs) const {
  return

      (getSnssai() == rhs.getSnssai()) &&

      (getStatus() == rhs.getStatus())

          ;
}

bool NssaaStatusRm::operator!=(const NssaaStatusRm& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const NssaaStatusRm& o) {
  j           = nlohmann::json();
  j["snssai"] = o.m_Snssai;
  j["status"] = o.m_Status;
}

void from_json(const nlohmann::json& j, NssaaStatusRm& o) {
  j.at("snssai").get_to(o.m_Snssai);
  j.at("status").get_to(o.m_Status);
}

oai::model::common::Snssai NssaaStatusRm::getSnssai() const {
  return m_Snssai;
}
void NssaaStatusRm::setSnssai(oai::model::common::Snssai const& value) {
  m_Snssai = value;
}
oai::model::common::AuthStatus NssaaStatusRm::getStatus() const {
  return m_Status;
}
void NssaaStatusRm::setStatus(oai::model::common::AuthStatus const& value) {
  m_Status = value;
}

}  // namespace oai::model::common
