version: '3.8'

services:
    gnb_mono_tdd:
        image: oaisoftwarealliance/oai-gnb:develop
        privileged: true
        network_mode: "host"
        container_name: sa-b210-gnb
        #entrypoint: /bin/bash -c "sleep infinity"
        environment:
            USE_B2XX: 'yes'
            USE_VOLUMED_CONF: True
            USE_ADDITIONAL_OPTIONS: --sa --continuous-tx --log_config.global_log_options level,nocolor,time,line_num,function --opt.type wireshark
        volumes:
            -  /dev/bus/usb/:/dev/bus/usb/
            - ./gnb-n77.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            # pgrep does NOT work
            test: /bin/bash -c "ps aux | grep -v grep | grep -c softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
