/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces. © 2022, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.7
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * WirelineServiceAreaRestriction.h
 *
 *
 */

#ifndef WirelineServiceAreaRestriction_H_
#define WirelineServiceAreaRestriction_H_

#include "RestrictionType.h"
#include "WirelineArea.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::model::common {

/// <summary>
///
/// </summary>
class WirelineServiceAreaRestriction {
 public:
  WirelineServiceAreaRestriction();
  virtual ~WirelineServiceAreaRestriction() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const WirelineServiceAreaRestriction& rhs) const;
  bool operator!=(const WirelineServiceAreaRestriction& rhs) const;

  /////////////////////////////////////////////
  /// WirelineServiceAreaRestriction members

  /// <summary>
  ///
  /// </summary>
  oai::model::common::RestrictionType getRestrictionType() const;
  void setRestrictionType(oai::model::common::RestrictionType const& value);
  bool restrictionTypeIsSet() const;
  void unsetRestrictionType();
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::model::common::WirelineArea> getAreas() const;
  void setAreas(std::vector<oai::model::common::WirelineArea> const& value);
  bool areasIsSet() const;
  void unsetAreas();

  friend void to_json(
      nlohmann::json& j, const WirelineServiceAreaRestriction& o);
  friend void from_json(
      const nlohmann::json& j, WirelineServiceAreaRestriction& o);

 protected:
  oai::model::common::RestrictionType m_RestrictionType;
  bool m_RestrictionTypeIsSet;
  std::vector<oai::model::common::WirelineArea> m_Areas;
  bool m_AreasIsSet;
};

}  // namespace oai::model::common

#endif /* WirelineServiceAreaRestriction_H_ */
