apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-nrf.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: http1
      # Port accessible outside cluster
      port: {{ .Values.config.nrfInterfacePortForSBI }}
      # Port to forward config inside the pod
      targetPort: {{ .Values.config.nrfInterfacePortForSBI }}
      protocol: TCP
    - name: http2
      # Port accessible outside cluster
      port: {{ .Values.config.nrfInterfaceHttp2PortForSBI }}
      # Port to forward to inside the pod
      targetPort: {{ .Values.config.nrfInterfaceHttp2PortForSBI }}
      protocol: TCP
  selector:
    {{- include "oai-nrf.selectorLabels" . | nindent 4 }}
{{- if eq .Values.kubernetesType "Openshift" }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Chart.Name }}-svc
  labels:
    {{- include "oai-nrf.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http1
  to:
   kind: Service
   name: {{ .Chart.Name }}-svc
   weight: 100
{{- end }}
