version: '3.8'
services:
    omec-gnbsim-0:
        container_name: omec-gnbsim-0
        image: 5gc-gnbsim:tag-to-use
        privileged: true
        command: bash -c "/gnbsim/bin/gnbsim --cfg /gnbsim/bin/gnbsim.yaml && sleep infinity"
        networks:
            public_net:
                ipv4_address: 192.168.70.171
        volumes:
            - ./omec-gnbsim-config-0.yaml:/gnbsim/bin/gnbsim.yaml
    omec-gnbsim-1:
        container_name: omec-gnbsim-1
        image: 5gc-gnbsim:tag-to-use
        privileged: true
        command: bash -c "/gnbsim/bin/gnbsim --cfg /gnbsim/bin/gnbsim.yaml && sleep infinity"
        networks:
            public_net:
                ipv4_address: 192.168.70.172
        volumes:
            - ./omec-gnbsim-config-1.yaml:/gnbsim/bin/gnbsim.yaml
    omec-gnbsim-2:
        container_name: omec-gnbsim-2
        image: 5gc-gnbsim:tag-to-use
        privileged: true
        command: bash -c "/gnbsim/bin/gnbsim --cfg /gnbsim/bin/gnbsim.yaml && sleep infinity"
        networks:
            public_net:
                ipv4_address: 192.168.70.173
        volumes:
            - ./omec-gnbsim-config-2.yaml:/gnbsim/bin/gnbsim.yaml
    omec-gnbsim-3:
        container_name: omec-gnbsim-3
        image: 5gc-gnbsim:tag-to-use
        privileged: true
        command: bash -c "/gnbsim/bin/gnbsim --cfg /gnbsim/bin/gnbsim.yaml && sleep infinity"
        networks:
            public_net:
                ipv4_address: 192.168.70.174
        volumes:
            - ./omec-gnbsim-config-3.yaml:/gnbsim/bin/gnbsim.yaml
    omec-gnbsim-4:
        container_name: omec-gnbsim-4
        image: 5gc-gnbsim:tag-to-use
        privileged: true
        command: bash -c "/gnbsim/bin/gnbsim --cfg /gnbsim/bin/gnbsim.yaml && sleep infinity"
        networks:
            public_net:
                ipv4_address: 192.168.70.175
        volumes:
            - ./omec-gnbsim-config-4.yaml:/gnbsim/bin/gnbsim.yaml
    omec-gnbsim-5:
        container_name: omec-gnbsim-5
        image: 5gc-gnbsim:tag-to-use
        privileged: true
        command: bash -c "/gnbsim/bin/gnbsim --cfg /gnbsim/bin/gnbsim.yaml && sleep infinity"
        networks:
            public_net:
                ipv4_address: 192.168.70.176
        volumes:
            - ./omec-gnbsim-config-5.yaml:/gnbsim/bin/gnbsim.yaml
    omec-gnbsim-6:
        container_name: omec-gnbsim-6
        image: 5gc-gnbsim:tag-to-use
        privileged: true
        command: bash -c "/gnbsim/bin/gnbsim --cfg /gnbsim/bin/gnbsim.yaml && sleep infinity"
        networks:
            public_net:
                ipv4_address: 192.168.70.177
        volumes:
            - ./omec-gnbsim-config-6.yaml:/gnbsim/bin/gnbsim.yaml
    omec-gnbsim-7:
        container_name: omec-gnbsim-7
        image: 5gc-gnbsim:tag-to-use
        privileged: true
        command: bash -c "/gnbsim/bin/gnbsim --cfg /gnbsim/bin/gnbsim.yaml && sleep infinity"
        networks:
            public_net:
                ipv4_address: 192.168.70.178
        volumes:
            - ./omec-gnbsim-config-7.yaml:/gnbsim/bin/gnbsim.yaml
networks:
    public_net:
        external:
            name: demo-oai-public-net
